// examples/demo/src/App.tsx
import type { ReactNode } from "react";
import { useState } from "react";
import clsx from "clsx";
import { setTheme } from "./arvia-theme";
import { Badge } from "./components/badge.arv";
import { Button, type ButtonProps } from "./components/button.arv";
import { Card } from "./components/card.arv";
import { Stack } from "./components/stack.arv";
import { Text } from "./components/text.arv";
import { Recipes } from "./Recipes";

const SIZES = ["sm", "md", "lg"] as const;
const TONES = ["primary", "danger", "ghost"] as const;
const BADGE_TONES = ["neutral", "success", "warning", "danger"] as const;

function DemoButton(
  props: ButtonProps & { children: ReactNode; disabled?: boolean; onClick?: () => void },
) {
  const styles = Button({ size: props.size, tone: props.tone });
  return (
    <button className={styles.root} disabled={props.disabled} onClick={props.onClick} type="button">
      <span className={styles.icon}>✦</span>
      <span className={styles.label}>{props.children}</span>
    </button>
  );
}

function Section(props: { title: string; children: ReactNode }) {
  const card = Card();
  return (
    <section className={card.root}>
      <header className={card.header}>
        <Heading size="lg">{props.title}</Heading>
      </header>
      <div className={card.body}>{props.children}</div>
    </section>
  );
}

function Heading(props: { size?: "lg" | "xl" | "2xl"; children: ReactNode }) {
  return (
    <h2 className={Text({ size: props.size ?? "lg", weight: "bold" }).root}>{props.children}</h2>
  );
}

function Tab(props: { active: boolean; onClick: () => void; children: ReactNode }) {
  const styles = Button({
    tone: props.active ? "primary" : "ghost",
    size: "sm",
  });
  return (
    <button type="button" className={styles.root} onClick={props.onClick}>
      <span className={styles.label}>{props.children}</span>
    </button>
  );
}

export function App() {
  const [view, setView] = useState<"playground" | "recipes">("playground");
  const page = Stack({ gap: "5" });
  const row = Stack({ direction: "row", gap: "3", align: "center", wrap: "yes" });

  return (
    <main className={page.root} style={{ maxWidth: 720, margin: "0 auto", padding: 24 }}>
      <header>
        <div className={row.root} style={{ justifyContent: "space-between" }}>
          <Heading size="2xl">Arvia Playground</Heading>
          <div className={row.root}>
            <DemoButton size="sm" tone="ghost" onClick={() => setTheme("light")}>
              Light
            </DemoButton>
            <DemoButton size="sm" tone="ghost" onClick={() => setTheme("dark")}>
              Dark
            </DemoButton>
          </div>
        </div>
        <p className={Text({ tone: "muted" }).root}>
          Every style on this page is compiled from <code>.arv</code> files — zero runtime CSS.
        </p>
        <div className={row.root} style={{ marginTop: 16 }}>
          <Tab active={view === "playground"} onClick={() => setView("playground")}>
            Playground
          </Tab>
          <Tab active={view === "recipes"} onClick={() => setView("recipes")}>
            Recipes
          </Tab>
        </div>
      </header>

      {view === "recipes" ? (
        <Recipes />
      ) : (
        <>
          <Section title="Button — sizes × tones, compound variant on sm + danger">
            <div className={Stack({ gap: "4" }).root}>
              {TONES.map((tone) => (
                <div key={tone} className={row.root}>
                  {SIZES.map((size) => (
                    <DemoButton key={size} size={size} tone={tone}>
                      {tone} {size}
                    </DemoButton>
                  ))}
                  <DemoButton tone={tone} disabled>
                    disabled
                  </DemoButton>
                </div>
              ))}
            </div>
          </Section>

          <Section title="Badge — tone variants">
            <div className={row.root}>
              {BADGE_TONES.map((tone) => (
                <span key={tone} className={Badge({ tone }).root}>
                  {tone}
                </span>
              ))}
            </div>
          </Section>

          <Section title="Text — typography tokens">
            <div className={Stack({ gap: "2" }).root}>
              <p className={Text({ size: "2xl", weight: "bold" }).root}>
                The five boxing wizards (2xl)
              </p>
              <p className={Text({ size: "xl", weight: "medium" }).root}>
                The five boxing wizards (xl)
              </p>
              <p className={Text({ size: "lg" }).root}>The five boxing wizards (lg)</p>
              <p className={Text({ size: "md" }).root}>The five boxing wizards (md)</p>
              <p className={Text({ size: "sm", tone: "muted" }).root}>
                The five boxing wizards (sm, muted)
              </p>
              <p className={Text({ tone: "primary", weight: "medium" }).root}>Primary tone</p>
            </div>
          </Section>

          <Section title="Button — responsive (resize viewport)">
            <p className={Text({ size: "sm", tone: "muted" }).root}>
              The default (small) button scales up via <code>@media</code> ranges in{" "}
              <code>base</code>: bumps padding/font at 768px (<code>md..</code>) and 1024px (
              <code>lg..</code>).
            </p>
            <div className={row.root}>
              <DemoButton tone="primary">responsive</DemoButton>
            </div>
          </Section>

          <Section title="Card — container queries (resize the box)">
            <ContainerCardDemo />
          </Section>

          <Section title="Card — recipe (Surface) + slots">
            <CardDemo />
          </Section>
        </>
      )}
    </main>
  );
}

function ContainerCardDemo() {
  const card = Card();
  return (
    <div
      className={card.root}
      style={{
        resize: "horizontal",
        overflow: "auto",
        minWidth: 200,
        maxWidth: "100%",
        width: 360,
      }}
    >
      <header className={card.header}>Container query demo</header>
      <div className={card.body}>
        <p className={Text({ tone: "muted", size: "sm" }).root}>
          Drag the handle — layout switches to horizontal past the <code>wide</code> container token
          (560px).
        </p>
        <span className={Badge({ tone: "neutral" }).root}>stacked → row</span>
      </div>
    </div>
  );
}

function CardDemo() {
  const card = Card();
  return (
    <div className={card.root}>
      <header className={card.header}>Invoice #1042</header>
      <div className={card.body}>
        <p className={Text({ tone: "muted" }).root}>
          The header, body and footer of this card are separate slots styled by one component.
        </p>
      </div>
      <footer className={clsx(card.footer, Text({ size: "sm", tone: "muted" }).root)}>
        Due in 14 days
      </footer>
    </div>
  );
}

// examples/vue-demo/src/App.vue
<script setup lang="ts">
import { setTheme } from "./arvia-theme";
import { Badge } from "./components/badge.arv";
import { Button, type ButtonProps } from "./components/button.arv";
import { Stack } from "./components/stack.arv";

const SIZES = ["sm", "md", "lg"] as const satisfies readonly ButtonProps["size"][];
const TONES = ["primary", "danger", "ghost"] as const satisfies readonly ButtonProps["tone"][];
const BADGE_TONES = ["neutral", "success", "warning", "danger"] as const;

const page = Stack({ gap: "5" });
const row = Stack({ direction: "row", gap: "3", align: "center", wrap: "yes" });
const ghostSm = Button({ size: "sm", tone: "ghost" });
</script>

<template>
  <main :class="page.root" style="max-width: 720px; margin: 0 auto; padding: 24px">
    <header :class="row.root" style="justify-content: space-between">
      <h1>Arvia + Vue</h1>
      <div :class="row.root">
        <button type="button" :class="ghostSm.root" @click="setTheme('light')">
          <span :class="ghostSm.label">Light</span>
        </button>
        <button type="button" :class="ghostSm.root" @click="setTheme('dark')">
          <span :class="ghostSm.label">Dark</span>
        </button>
      </div>
    </header>

    <p>Every style on this page is compiled from <code>.arv</code> files — zero runtime CSS.</p>

    <section :class="Stack({ gap: '4' }).root">
      <h2>Button — sizes × tones, compound variant on sm + danger</h2>
      <div v-for="tone in TONES" :key="tone" :class="row.root">
        <button
          v-for="size in SIZES"
          :key="size"
          type="button"
          :class="Button({ size, tone }).root"
        >
          <span :class="Button({ size, tone }).icon">✦</span>
          <span :class="Button({ size, tone }).label">{{ tone }} {{ size }}</span>
        </button>
        <button type="button" :class="Button({ tone }).root" disabled>
          <span :class="Button({ tone }).label">disabled</span>
        </button>
      </div>
    </section>

    <section :class="Stack({ gap: '4' }).root">
      <h2>Badge — tone variants</h2>
      <div :class="row.root">
        <span v-for="tone in BADGE_TONES" :key="tone" :class="Badge({ tone }).root">
          {{ tone }}
        </span>
      </div>
    </section>
  </main>
</template>
